version: "3.8"

networks:
  paddy-bridge:
    driver: bridge

services:
  paddy-backend:
    container_name: paddy-backend
    networks:
      paddy-bridge:
        aliases:
          - paddy.backend.io
    build: .
    restart: on-failure
    ports:
      - "443:80" # Redirect https traffic to http because we are using a terminating LB
      - "80:80"
    env_file:
      - ".env"

  emqx1:
    image: emqx:5.4.1
    container_name: emqx1
    restart: on-failure
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
      - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
      - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5
#    volumes:
#      - "./emqx/emqx.conf:/opt/emqx/etc/emqx.conf:ro"
    networks:
      paddy-bridge:
        aliases:
          - node1.emqx.io
    ports:
      - "1883:1883" # Redirect mqtts traffic to mqtt because we are using a terminating LB
#      - "8083:8083"
#      - "8084:8084"
#      - "8883:8883"
      - "18083:18083"

  neo4j:
    image: neo4j:5.16.0
    container_name: neo4j
    restart: on-failure
    volumes:
      - /home/chronos/neo4j/data:/data
      - /home/chronos/neo4j/logs:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/bonkersdbobcat