quarkus:
  package:
    output-name: paddy-backend

  devservices:
    enabled: false

  http:
    port: 80
    root-path: /api/v1
    access-log:
      enabled: true
    auth:
      permission:
        authorizer:
          paths: /*
          policy: paddy-http-authorizer
    cors:
      origins: "*" # TODO: fix this later to proper origins
      headers: accept, authorization, content-type, x-requested-with
      methods: OPTIONS, GET, POST, PATCH, PUT, DELETE

  rest-client:
    jwt:
      http2: true