quarkus:
  package:
    output-name: paddy-backend

  devservices:
    enabled: false

  http:
    port: 80
    root-path: /api/v1
    access-log:
      enabled: true
    auth:
      permission:
        authorizer:
          paths: /*
          policy: paddy-http-authorizer

  rest-client:
    jwt:
      http2: true